### PR TITLE
Support for IDEA version 2022.2

### PR DESCRIPTION
**Pull request by chachako**

### CODE REVIEW

**Comment by Starmel** [comment]
@suusan2go please release the new version

**Comment by Starmel** [comment]
Did build for the 2022.2

[kotlin-fill-class-1.0.12.jar.zip](https://github.com/suusan2go/kotlin-fill-class/files/9260560/kotlin-fill-class-1.0.12.jar.zip)

**Comment by rsobies** [comment]
can we just add this line in gradle
`
patchPluginXml {
        sinceBuild = '191.8026.42'
        untilBuild='222.*'
    }
`

**Comment by suusan2go** [comment]
Sorry for the late reply,  released as 1.0.14 including support for 2022.2 https://github.com/suusan2go/kotlin-fill-class/commit/632ee2caae4a9ee4a0f1af3b035ecbdcd8e0cbd4

**Pull request closed without merging**
